### ISSUE TITLE
Plugin fails when secret values contain some special characters

### ISSUE THREAD

**Issue by fd-jonathanlinn** [buildkite-plugins/vault-secrets-buildkite-plugin#16]
I've been working on a partial fix for this in a fork but wanted to document it here.  As the plugin uses the `yaml` formatting option to help it pull secrets from Vault, this means that special characters can cause all kinds of issues, in particular pipes `|` and newlines on things like PEM files.  

While there's built in functionality to handle PEM files for SSH-related purposes by adding them to the ssh-agent, this doesn't cover all use cases, and the plugin should be able to handle these situations.  

To tackle the issue of pipes and some bash-specific patterns, my upstream fix escapes values on the fly and then wraps them in double quotes.  This has worked fine for ourselves, but because certificates maintain newlines **and** begin `|- ` they cause issues.  

We should explore how to handle these occurrences - maybe moving to `json` output format for a start and going from there so that secrets come pre-wrapped in quotes and newlines are escaped?  I'm on the Buildkite Community Slack as \@Jonny as well if that's easier 🙂

**Comment by jeremybumsted** [comment]
This should be resolved in #19 :)
