### ISSUE TITLE
Is it possible to add OIDC as an auth method?

### ISSUE THREAD

**Issue by yob** [buildkite-plugins/vault-secrets-buildkite-plugin#25]
Now that [Buildkite supports OIDC](https://buildkite.com/changelog/197-oidc-support-is-now-available) in jobs, is it possible to use OIDC tokens to auth with vault?

I'm not super familiar with vault - I'm played around with it but never used it in prod. I believe it supports OIDC for authentication though, and I assume (but haven't verified) that it could be configured to trust Buildkite issued OIDC tokens. I assume you could configure policies like "allow OIDC tokens from pipeline foo to fetch secrets from prefix `data/buildkite/pipelines/foo/*`"

**Comment by jeremybumsted** [comment]
@yob yeah! As a first step, I've added support for using `jwt` as an auth method here: #32

**Comment by yob** [comment]
oh yer, I see some internal experimentation with OIDC and vault  settled on jwt auth as being the better option anyway. Perfect ✨
