### ISSUE TITLE
Buildkite Support request to take over maintaining/ownership of this plugin

### ISSUE THREAD

**Issue by jeremybumsted** [buildkite-plugins/vault-secrets-buildkite-plugin#4]
Hey @mikeknox, 

I am a Support Engineer at Buildkite and I'm reaching out as we'd love to take over maintaining this plugin! If you'd like to transfer ownership of this repo to [Buildkite Plugins](https://github.com/buildkite-plugins) we would be more than happy to continue maintaining this 😄 

Cheers,

Jeremy

**Comment by jeremybumsted** [comment]
@mikeknox Awesome thanks for the quick reply!

You shouldn't need to do more than [follow the steps here](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account) and then  I can verify once completed. 👍

**Comment by mikeknox** [comment]
@jeremybumsted,
I get the following error when attempting to transfer:
```You don’t have the permission to create public repositories on buildkite-plugins```

**Comment by jeremybumsted** [comment]
@mikeknox So this is my bad, I forgot that you needed to have `create` permissions on the target GitHub organization in order to transfer the repository 😞. Because I'm not able to add you to the organization, my suggestion at this point would be to transfer the organization to me, and then I can transfer it to [Buildkite Plugins](https://github.com/buildkite-plugins)

Let me know if that'll work for you 😄

**Comment by jeremybumsted** [comment]
Hey @mikeknox 👋  Just wanted to follow up on this - would the above suggestion work for you for transferring the repo?

**Comment by mikeknox** [comment]
@jeremybumsted , yes that oks, transfer has been initiated

**Comment by jeremybumsted** [comment]
@mikeknox Thanks very much! I've now moved this repo over to the buildkite-plugins org, and we'll take care of it from here!
