### ISSUE TITLE
JSON secrets break the plugin

### ISSUE THREAD

**Issue by ClayShentrup** [buildkite-plugins/vault-secrets-buildkite-plugin#47]
we have some secrets which are a JSON string. this leads to the following error.

```
/etc/buildkite-agent/plugins/github-robot-car-cruise-vault-secrets-buildkite-plugin-git-v2-0-0/hooks/environment: line 133: PRIVATE: command not found
```

the cause? this apparently isn't bash escaped correctly.

https://github.com/buildkite-plugins/vault-secrets-buildkite-plugin/blob/master/hooks/environment#L36

here are some techniques gemini suggested:

Bash
JSON_STRING=$(get_json)
ESCAPED_JSON=$(jq -R '.' <<< "$JSON_STRING")  
export MY_VAR="$ESCAPED_JSON"

Method 2: Using sed
Bash
JSON_STRING=$(get_json)
ESCAPED_JSON=$(sed 's/"/\\"/g; s/\\/\\\\/g; s/\$/\\$/g' <<< "$JSON_STRING")
export MY_VAR="$ESCAPED_JSON"

thank you

**Comment by jeremybumsted** [comment]
@ClayShentrup thanks for raising this! I just wanted to verify you're submitting this issue on the correct plugin. In the error message you shared I can see the plugin checkout path is checking out a different vault secrets plugin:

`github-robot-car-cruise-vault-secrets-buildkite-plugin-git-v2-0-0`

In either case I'm taking a look at this, but I just wanted to verify you're seeing the same thing on this plugin too.

**Comment by ClayShentrup** [comment]
yeah that's just our (unmodified) fork of it in the cruise enterprise
GitHub.

**Comment by ivannalisetska** [comment]
Hey, fixed the issue PR https://github.com/buildkite-plugins/vault-secrets-buildkite-plugin/pull/51

**Comment by ivannalisetska** [comment]
Hey, fixed the issue PR https://github.com/buildkite-plugins/vault-secrets-buildkite-plugin/pull/51
